b

In [1]:
import pandas as pd
import numpy as np

In [2]:
file1 = '../data/MIG_28122020103234499.csv'

In [3]:
migration = pd.read_csv(file1)

C:\Users\Pablo\anaconda3\envs\migration_flows\lib\site-packages\IPython\core\interactiveshell.py:3146: DtypeWarning: Columns (11,12) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,


In [4]:
migration.head()

CO2 Country of birth/nationality  VAR  \
0  AFG                  Afghanistan  B11   
1  AFG                  Afghanistan  B11   
2  AFG                  Afghanistan  B11   
3  AFG                  Afghanistan  B11   
4  AFG                  Afghanistan  B11   

                                       Variable  GEN Gender  COU    Country  \
0  Inflows of foreign population by nationality  TOT  Total  AUS  Australia   
1  Inflows of foreign population by nationality  TOT  Total  AUS  Australia   
2  Inflows of foreign population by nationality  TOT  Total  AUS  Australia   
3  Inflows of foreign population by nationality  TOT  Total  AUS  Australia   
4  Inflows of foreign population by nationality  TOT  Total  AUS  Australia   

    YEA  Year   Value Flag Codes Flags  
0  2000  2000   887.0        NaN   NaN  
1  2001  2001   456.0        NaN   NaN  
2  2002  2002   660.0        NaN   NaN  
3  2003  2003  1015.0        NaN   NaN  
4  2004  2004  1340.0        NaN   NaN

In [5]:
migration.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 477776 entries, 0 to 477775
Data columns (total 13 columns):
 #   Column                        Non-Null Count   Dtype  
---  ------                        --------------   -----  
 0   CO2                           477776 non-null  object 
 1   Country of birth/nationality  477776 non-null  object 
 2   VAR                           477776 non-null  object 
 3   Variable                      477776 non-null  object 
 4   GEN                           477776 non-null  object 
 5   Gender                        477776 non-null  object 
 6   COU                           477776 non-null  object 
 7   Country                       477776 non-null  object 
 8   YEA                           477776 non-null  int64  
 9   Year                          477776 non-null  int64  
 10  Value                         477749 non-null  float64
 11  Flag Codes                    27 non-null      object 
 12  Flags                         27 non-null   

In [6]:
migration.CO2.unique()

array(['AFG', 'ALB', 'DZA', 'AND', 'AGO', 'ATG', 'ARG', 'ARM', 'AUS',
       'AUT', 'AZE', 'BHS', 'BHR', 'BGD', 'BRB', 'BLR', 'BEL', 'BLZ',
       'BEN', 'BMU', 'BTN', 'BOL', 'BIH', 'BWA', 'BRA', 'BRN', 'BGR',
       'BFA', 'BDI', 'KHM', 'CMR', 'CAN', 'CPV', 'CAF', 'TCD', 'CHL',
       'CHN', 'COL', 'COM', 'COG', 'COK', 'CRI', 'CIV', 'HRV', 'CUB',
       'CYP', 'CZE', 'PRK', 'COD', 'DNK', 'DJI', 'DMA', 'DOM', 'ECU',
       'EGY', 'SLV', 'GNQ', 'ERI', 'EST', 'ETH', 'FJI', 'FIN', 'CSK',
       'SUN', 'YUCS', 'FRA', 'GAB', 'GMB', 'GEO', 'DEU', 'GHA', 'GRC',
       'GRD', 'GUM', 'GTM', 'GIN', 'GNB', 'GUY', 'HTI', 'HND', 'HKG',
       'HUN', 'ISL', 'IND', 'IDN', 'IRN', 'IRQ', 'IRL', 'ISR', 'ITA',
       'JAM', 'JPN', 'JOR', 'KAZ', 'KEN', 'KIR', 'KOR', 'KWT', 'KGZ',
       'LAO', 'LVA', 'LBN', 'LSO', 'LBR', 'LBY', 'LIE', 'LTU', 'LUX',
       'MAC', 'MKD', 'MDG', 'MWI', 'MYS', 'MDV', 'MLI', 'MLT', 'MHL',
       'MRT', 'MUS', 'MEX', 'FSM', 'MDA', 'MCO', 'MNG', 'MNE', 'MAR',
       'MOZ', 'MMR'

In [26]:
migration['Country of birth/nationality'].unique()

array(['Afghanistan', 'Albania', 'Algeria', 'Andorra', 'Angola',
       'Antigua and Barbuda', 'Argentina', 'Armenia', 'Australia',
       'Austria', 'Azerbaijan', 'Bahamas', 'Bahrain', 'Bangladesh',
       'Barbados', 'Belarus', 'Belgium', 'Belize', 'Benin', 'Bermuda',
       'Bhutan', 'Bolivia', 'Bosnia and Herzegovina', 'Botswana',
       'Brazil', 'Brunei Darussalam', 'Bulgaria', 'Burkina Faso',
       'Burundi', 'Cambodia', 'Cameroon', 'Canada', 'Cape Verde',
       'Central African Republic', 'Chad', 'Chile', 'China', 'Colombia',
       'Comoros', 'Congo', 'Cook Islands', 'Costa Rica', "Côte d'Ivoire",
       'Croatia', 'Cuba', 'Cyprus', 'Czech Republic',
       "Democratic People's Republic of Korea",
       'Democratic Republic of the Congo', 'Denmark', 'Djibouti',
       'Dominica', 'Dominican Republic', 'Ecuador', 'Egypt',
       'El Salvador', 'Equatorial Guinea', 'Eritrea', 'Estonia',
       'Ethiopia', 'Fiji', 'Finland', 'Former Czechoslovakia',
       'Former USSR', 'Form

In [27]:
migration.VAR.unique()

array(['B11', 'B12', 'B14', 'B13', 'B15', 'B16'], dtype=object)

In [28]:
migration.Variable.unique()

array(['Inflows of foreign population by nationality',
       'Outflows of foreign population by nationality',
       'Stock of foreign-born population by country of birth',
       'Inflows of asylum seekers by nationality',
       'Stock of foreign population by nationality',
       'Acquisition of nationality by country of former nationality'],
      dtype=object)

In [29]:
migration.GEN.unique()

array(['TOT'], dtype=object)

In [30]:
migration.Gender.unique()

array(['Total'], dtype=object)

In [31]:
migration.COU.unique()

array(['AUS', 'AUT', 'BEL', 'CAN', 'CZE', 'DNK', 'FIN', 'FRA', 'DEU',
       'GRC', 'HUN', 'ISL', 'IRL', 'ITA', 'JPN', 'KOR', 'LUX', 'MEX',
       'NLD', 'NZL', 'NOR', 'POL', 'SVK', 'ESP', 'SWE', 'CHE', 'TUR',
       'GBR', 'USA', 'CHL', 'EST', 'SVN', 'PRT', 'ISR', 'LVA'],
      dtype=object)

In [32]:
migration.Country.unique()

array(['Australia', 'Austria', 'Belgium', 'Canada', 'Czech Republic',
       'Denmark', 'Finland', 'France', 'Germany', 'Greece', 'Hungary',
       'Iceland', 'Ireland', 'Italy', 'Japan', 'Korea', 'Luxembourg',
       'Mexico', 'Netherlands', 'New Zealand', 'Norway', 'Poland',
       'Slovak Republic', 'Spain', 'Sweden', 'Switzerland', 'Turkey',
       'United Kingdom', 'United States', 'Chile', 'Estonia', 'Slovenia',
       'Portugal', 'Israel', 'Latvia'], dtype=object)

In [33]:
migration.YEA.unique()

array([2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010,
       2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020],
      dtype=int64)

In [34]:
migration.Year.unique()

array([2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010,
       2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020],
      dtype=int64)

In [36]:
migration['Flag Codes'].unique()

array([nan, 'e'], dtype=object)

In [37]:
migration.Flags.unique()

array([nan, 'Estimated value'], dtype=object)

In [8]:
migration_inflows = migration[migration.Variable == 'Inflows of foreign population by nationality']

In [9]:
migration_inflows.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 96045 entries, 0 to 475074
Data columns (total 13 columns):
 #   Column                        Non-Null Count  Dtype  
---  ------                        --------------  -----  
 0   CO2                           96045 non-null  object 
 1   Country of birth/nationality  96045 non-null  object 
 2   VAR                           96045 non-null  object 
 3   Variable                      96045 non-null  object 
 4   GEN                           96045 non-null  object 
 5   Gender                        96045 non-null  object 
 6   COU                           96045 non-null  object 
 7   Country                       96045 non-null  object 
 8   YEA                           96045 non-null  int64  
 9   Year                          96045 non-null  int64  
 10  Value                         96018 non-null  float64
 11  Flag Codes                    27 non-null     object 
 12  Flags                         27 non-null     object 
dtype